# Generated by Django 3.0.3 on 2020-02-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtle_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
