# Generated by Django 3.0.3 on 2020-02-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreChecksData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.IntegerField(db_index=True, default=0)),
                ('count', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'xtle_store_check_data',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_unit_mtime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('max_unit_revision', models.IntegerField(blank=True, db_index=True, default=0)),
                ('critical_checks', models.IntegerField(db_index=True, default=0)),
                ('pending_suggestions', models.IntegerField(db_index=True, default=0)),
                ('total_words', models.IntegerField(db_index=True, default=0)),
                ('translated_words', models.IntegerField(db_index=True, default=0)),
                ('fuzzy_words', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'xtle_store_data',
            },
        ),
        migrations.CreateModel(
            name='TPChecksData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.IntegerField(db_index=True, default=0)),
                ('count', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'xtle_tp_check_data',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TPData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_unit_mtime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('max_unit_revision', models.IntegerField(blank=True, db_index=True, default=0)),
                ('critical_checks', models.IntegerField(db_index=True, default=0)),
                ('pending_suggestions', models.IntegerField(db_index=True, default=0)),
                ('total_words', models.IntegerField(db_index=True, default=0)),
                ('translated_words', models.IntegerField(db_index=True, default=0)),
                ('fuzzy_words', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'xtle_tp_data',
            },
        ),
    ]
