# Generated by Django 3.0.3 on 2020-02-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xtle_statistics', '0001_initial'),
        ('xtle_tp', '0001_initial'),
        ('xtle_store', '0001_initial'),
        ('xtle_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpdata',
            name='last_created_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_created_for_tpdata', to='xtle_store.Unit'),
        ),
        migrations.AddField(
            model_name='tpdata',
            name='last_submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpdata_stats_data', to='xtle_statistics.Submission'),
        ),
        migrations.AddField(
            model_name='tpdata',
            name='tp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='xtle_tp.TranslationProject'),
        ),
        migrations.AddField(
            model_name='tpchecksdata',
            name='tp',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='check_data', to='xtle_tp.TranslationProject'),
        ),
        migrations.AddField(
            model_name='storedata',
            name='last_created_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_created_for_storedata', to='xtle_store.Unit'),
        ),
        migrations.AddField(
            model_name='storedata',
            name='last_submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storedata_stats_data', to='xtle_statistics.Submission'),
        ),
        migrations.AddField(
            model_name='storedata',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='xtle_store.Store'),
        ),
        migrations.AddField(
            model_name='storechecksdata',
            name='store',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='check_data', to='xtle_store.Store'),
        ),
        migrations.AlterUniqueTogether(
            name='tpchecksdata',
            unique_together={('tp', 'category', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='tpchecksdata',
            index_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='storechecksdata',
            unique_together={('store', 'category', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='storechecksdata',
            index_together={('name', 'category')},
        ),
    ]
