# Generated by Django 3.0.3 on 2020-02-18 19:09

from django.db import migrations, models
import django.db.models.deletion
import xtle.core.mixins.treeitem


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xtle_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='ISO 639 language code for the language, possibly followed by an underscore (_) and an ISO 3166 country code. <a href="http://www.w3.org/International/articles/language-tags/">More information</a>', max_length=50, unique=True, verbose_name='Code')),
                ('fullname', models.CharField(max_length=255, verbose_name='Full Name')),
                ('specialchars', models.CharField(blank=True, help_text='Enter any special characters that users might find difficult to type', max_length=255, verbose_name='Special Characters')),
                ('nplurals', models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0, help_text='For more information, visit <a href="http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html">our page</a> on plural forms.', verbose_name='Number of Plurals')),
                ('pluralequation', models.CharField(blank=True, help_text='For more information, visit <a href="http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html">our page</a> on plural forms.', max_length=255, verbose_name='Plural Equation')),
                ('directory', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='xtle_app.Directory')),
            ],
            options={
                'db_table': 'xtle_app_language',
                'ordering': ['code'],
            },
            bases=(models.Model, xtle.core.mixins.treeitem.TreeItem),
        ),
    ]
