# Generated by Django 3.0.3 on 2020-02-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xtle_path', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('last_sync_revision', models.IntegerField(blank=True, null=True)),
                ('last_sync_mtime', models.DateTimeField(blank=True, null=True)),
                ('last_sync_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('staged_for_removal', models.BooleanField(default=False)),
                ('staged_for_merge', models.BooleanField(default=False)),
                ('resolve_conflict', models.IntegerField(blank=True, choices=[(0, ''), (1, 'xtle'), (2, 'fs')], default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
