# Generated by Django 3.0.3 on 2020-02-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xtle_project', '0001_initial'),
        ('xtle_fs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefs',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_fs', to='xtle_project.Project'),
        ),
    ]
