# Generated by Django 3.0.3 on 2020-02-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xtle_fs', '0002_storefs_project'),
        ('xtle_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefs',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fs', to='xtle_store.Store'),
        ),
    ]
