# Generated by Django 3.0.3 on 2020-02-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(db_index=True)),
                ('field', models.IntegerField(blank=True, db_index=True, null=True)),
                ('type', models.IntegerField(blank=True, db_index=True, null=True)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('revision', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'xtle_app_submission',
                'ordering': ['creation_time', 'pk'],
                'get_latest_by': 'creation_time',
                'base_manager_name': 'objects',
            },
        ),
    ]
