# Generated by Django 3.0.3 on 2020-02-18 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import xtle.core.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xtle_tp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xtle_store', '0001_initial'),
        ('xtle_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='quality_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xtle_store.QualityCheck'),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitter',
            field=models.ForeignKey(db_index=False, null=True, on_delete=models.SET(xtle.core.user.get_system_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xtle_store.Suggestion'),
        ),
        migrations.AddField(
            model_name='submission',
            name='translation_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xtle_tp.TranslationProject'),
        ),
        migrations.AddField(
            model_name='submission',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xtle_store.Unit'),
        ),
        migrations.AlterIndexTogether(
            name='submission',
            index_together={('submitter', 'creation_time')},
        ),
    ]
