# Generated by Django 3.0.3 on 2020-02-19 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import xtle.core.markup.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, help_text='Whether this page is active or not.', verbose_name='Active')),
                ('virtual_path', models.CharField(default='', help_text='/pages/', max_length=100, unique=True, verbose_name='Virtual Path')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('body', xtle.core.markup.fields.MarkupField(blank=True, verbose_name='Display Content')),
                ('url', models.URLField(blank=True, help_text='If set, this page will redirect to this URL', verbose_name='Redirect to URL')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, help_text='Whether this page is active or not.', verbose_name='Active')),
                ('virtual_path', models.CharField(default='', help_text='/pages/', max_length=100, unique=True, verbose_name='Virtual Path')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('body', xtle.core.markup.fields.MarkupField(blank=True, verbose_name='Display Content')),
                ('url', models.URLField(blank=True, help_text='If set, this page will redirect to this URL', verbose_name='Redirect to URL')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xtle_staticpages.LegalPage')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'document')},
            },
        ),
    ]
