# Generated by Django 3.0.3 on 2020-02-18 19:09

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, numbers and @/./+/-/_ characters', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Enter a valid username.', 'invalid')], verbose_name='Username')),
                ('email', models.EmailField(max_length=255, verbose_name='Email Address')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Full Name')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('is_superuser', models.BooleanField(db_index=True, default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='Superuser Status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('unit_rows', models.SmallIntegerField(default=9, verbose_name='Number of Rows')),
                ('score', models.FloatField(default=0, verbose_name='Score')),
                ('is_employee', models.BooleanField(default=False, verbose_name='Is employee?')),
                ('twitter', models.CharField(blank=True, max_length=15, null=True, verbose_name='Twitter')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Short Bio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
