# Generated by Django 3.0.3 on 2020-02-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xtle_accounts', '0001_initial'),
        ('xtle_language', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alt_src_langs',
            field=models.ManyToManyField(blank=True, db_index=True, limit_choices_to=models.Q(_negated=True, code='templates'), to='xtle_language.Language', verbose_name='Alternative Source Languages'),
        ),
    ]
