# Generated by Django 3.0.3 on 2020-02-29 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xtle_store', '0001_initial'),
        ('xtle_tp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTPScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.FloatField(db_index=True, default=0)),
                ('reviewed', models.IntegerField(db_index=True, default=0)),
                ('suggested', models.IntegerField(db_index=True, default=0)),
                ('translated', models.IntegerField(db_index=True, default=0)),
                ('tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='xtle_tp.TranslationProject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'xtle_user_tp_score',
                'abstract': False,
                'unique_together': {('date', 'tp', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserStoreScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.FloatField(db_index=True, default=0)),
                ('reviewed', models.IntegerField(db_index=True, default=0)),
                ('suggested', models.IntegerField(db_index=True, default=0)),
                ('translated', models.IntegerField(db_index=True, default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='xtle_store.Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'xtle_user_store_score',
                'abstract': False,
                'unique_together': {('date', 'store', 'user')},
            },
        ),
    ]
