# Generated by Django 3.0.3 on 2020-02-18 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import xtle.app.models.directory
import xtle.core.mixins.treeitem


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, validators=[xtle.app.models.directory.validate_no_slashes])),
                ('xtle_path', models.CharField(db_index=True, default='/', max_length=255, unique=True)),
                ('tp_path', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('obsolete', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_dirs', to='xtle_app.Directory')),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': (),
                'base_manager_name': 'objects',
            },
            bases=(models.Model, xtle.core.mixins.treeitem.CachedTreeItem),
        ),
        migrations.CreateModel(
            name='PermissionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_sets', to='xtle_app.Directory')),
                ('negative_permissions', models.ManyToManyField(db_index=True, related_name='permission_sets_negative', to='auth.Permission')),
                ('positive_permissions', models.ManyToManyField(db_index=True, related_name='permission_sets_positive', to='auth.Permission')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
