# Generated by Django 3.0.3 on 2020-02-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xtle_tp', '0001_initial'),
        ('xtle_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='tp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dirs', to='xtle_tp.TranslationProject'),
        ),
        migrations.AlterUniqueTogether(
            name='permissionset',
            unique_together={('user', 'directory')},
        ),
        migrations.AlterIndexTogether(
            name='directory',
            index_together={('obsolete', 'xtle_path'), ('obsolete', 'tp', 'tp_path')},
        ),
    ]
