# Generated by Django 3.0.3 on 2020-02-18 19:09

from django.db import migrations, models
import django.db.models.deletion
import xtle.core.mixins.treeitem


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xtle_project', '0001_initial'),
        ('xtle_app', '0001_initial'),
        ('xtle_language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xtle_path', models.CharField(db_index=True, editable=False, max_length=255, unique=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('directory', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='xtle_app.Directory')),
                ('language', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='xtle_language.Language')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xtle_project.Project')),
            ],
            options={
                'db_table': 'xtle_app_translationproject',
                'base_manager_name': 'objects',
                'unique_together': {('language', 'project'), ('project', 'language')},
            },
            bases=(models.Model, xtle.core.mixins.treeitem.CachedTreeItem),
        ),
    ]
