# Generated by Django 3.0.3 on 2020-02-18 16:42

import collections
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(blank=True, max_length=255, null=True, verbose_name='object ID')),
                ('key', models.CharField(db_index=True, max_length=255, verbose_name='Configuration key')),
                ('value', jsonfield.fields.JSONField(blank=True, default='', load_kwargs={'object_pairs_hook': collections.OrderedDict}, verbose_name='Configuration value')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_config', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'db_table': 'xtle_config',
                'ordering': ['pk'],
                'abstract': False,
                'index_together': {('content_type', 'object_pk')},
            },
        ),
    ]
