# Generated by Django 3.0.3 on 2020-03-18 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xtle_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='code',
            field=models.CharField(db_index=True, default=None, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(db_index=True, default=datetime.datetime(2020, 3, 18, 12, 30, 20, 676762, tzinfo=utc), max_length=64),
            preserve_default=False,
        ),
    ]
