# Generated by Django 3.0.3 on 2020-03-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtle_team', '0002_auto_20200318_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='all_languages',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='all_projects',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
