# Generated by Django 3.0.3 on 2020-03-20 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xtle_team', '0003_auto_20200320_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='admins',
            field=models.ManyToManyField(related_name='team_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='contributors',
            field=models.ManyToManyField(related_name='team_contributors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='reviewers',
            field=models.ManyToManyField(related_name='team_reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='translators',
            field=models.ManyToManyField(related_name='team_translators', to=settings.AUTH_USER_MODEL),
        ),
    ]
