# Generated by Django 3.0.3 on 2020-02-18 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='object ID')),
                ('key', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Revision key')),
                ('value', models.CharField(default='', max_length=255, verbose_name='Revision hash or numeric marker')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_revision', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'db_table': 'xtle_revision',
                'ordering': ['pk'],
                'abstract': False,
                'unique_together': {('content_type', 'object_id', 'key')},
                'index_together': {('object_id', 'content_type', 'key')},
            },
        ),
    ]
